### ISSUE TITLE
Traduzir as rotas para o português

### ISSUE THREAD

**Issue by carolinesalib** [boacausa/webplatform#108]
Verificar na gem I18n se é possível realizar a tradução das rotas. Exemplo:

* porumaboacausa.herokuapp.com/**ngos** > porumaboacausa.herokuapp.com/**ongs**
* porumaboacausa.herokuapp.com/**ngo_area** > porumaboacausa.herokuapp.com/**ong_area**
* porumaboacausa.herokuapp.com/**adoption/index** > porumaboacausa.herokuapp.com/**adocao**

**Comment by anibiamachado** [comment]
@carolinesalib, a rota não foi traduzida nas seguintes situações:

- Ao clicar na opção "Interessados em adoção": https://www.boacausa.org/ong_area/adoption_interests;
- Ao cadastrar um novo usuário: https://www.boacausa.org/ong_area/usuarios/new;
- Ao cadastrar um novo pet: https://www.boacausa.org/ong_area/pets/new;
- Ao cadastrar uma nova ONG: https://www.boacausa.org/ong_area/ongs/new;
- Assim que entrei com meu usuário que tem acesso apenas às adoções e ONGs, mostrou o seguinte endereço na barra: https://www.boacausa.org/#_=_

**Comment by anibiamachado** [comment]
@carolinesalib, ajustar apenas o endereço abaixo:

"https://www.boacausa.org/ong_area/inderessados_adocao" para "https://www.boacausa.org/ong_area/interessados_adocao"

**Comment by carolinesalib** [comment]
@anibiamachado bom olho haha
