### ISSUE TITLE
Notificar a ONG quando tiver novas adoções

### ISSUE THREAD

**Issue by carolinesalib** [boacausa/webplatform#113]
Na área de administração, exibir uma notificação sempre que alguém fazer um pedido de adoção pela página. Sugestão "O usuário Tiago Giusti acabou de registrar interesse em um pet da sua ONG". Ou, se quiser e não for complexo, já colocar o nome do pet na mensagem. Ao clicar na mensagem, levar para a página que lista os pedidos de adoção efetuado.

Issue origem: https://github.com/boacausa/webplatform/issues/40

---

**Resumo do que foi implementado:**

* Sempre que um usuário clicar em "adotar" na página de lista de adoção, sera criado uma notificação na área da ONG
* Ao clicar na notificação o usuário vai ser redirecionado para a página de interesse em adoção e a notificação vai ser marcada como "lida", o que faz com que esta não apareça mais na lista.

Quando tem notificação de interesse em adoção:
<img width="326" alt="image" src="https://user-images.githubusercontent.com/5773360/71181965-69fb2f80-2232-11ea-8c87-dfe3e0eeeb1a.png">

Quando não tem notificação de interesse em adoção:
<img width="352" alt="image" src="https://user-images.githubusercontent.com/5773360/71181851-37e9cd80-2232-11ea-9ff4-e5a7574c61e7.png">

Quem vai receber notificação:
- Todos os admins (por enquanto)
- Todos os usuários que tem alguma ONG selecionada no cadastro de usuário
  - Estes receberão notificações de pets cadastrados em sua ONG

**Obs.:** Mesmo tendo varias notificações o usuário sempre é redirecionado para a mesma página, pois não temos uma página exclusiva para cada interesse em adoção registrado. Isso é algo que podemos melhorar no futuro coletando feedback do pessoal da ONG.

**Comment by carolinesalib** [comment]
Tava pensando em fazer algo diferente nessa issue, o que vocês acham @giustin e @anibiamachado ?

1. Seria enviar emails diários com a lista das pessoas que se interessaram em adotar nas ultimas 24h
2. Ou é melhor ter notificações mesmo na área da ONG?

**Comment by anibiamachado** [comment]
> Tava pensando em fazer algo diferente nessa issue, o que vocês acham @giustin e @anibiamachado ?
> 
> 1. Seria enviar emails diários com a lista das pessoas que se interessaram em adotar nas ultimas 24h
> 2. Ou é melhor ter notificações mesmo na área da ONG?

A opção de enviar por e-mail é muito boa porque não obriga o pessoal da ONG a acessar o app sempre que precisar saber dessa informação. Pode ser que eles até esqueçam de fazer isso. Só acho que teria que ter, pelo menos, uma lista corrida das pessoas interessadas pelos pets em algum lugar lá no app, para ter a informação de forma íntegra.

**Comment by giustin** [comment]
@carolinesalib @anibiamachado acho as duas sugestões úteis @carolinesalib, e se ambas foram possíveis agora, devemos fazer, pelas razões que @anibiamachado comentou, pra quem usa o app frequente ou para quem não usa ser notificado e ir lá gerir os interessados.

**Comment by carolinesalib** [comment]
@giustin @anibiamachado no final das contas acabei implementando as notificações dentro do app, pois fiquei com medo de criar um "spam". Mas imagino que nem todo mundo vai lembrar de acessar o app, então talvez seja util ter o e-mail. Deveriamos fazer isso como algo opcional? E com que frequência?

**Comment by giustin** [comment]
@carolinesalib acho que agora pode ser padrão, depois validamos se precisa o usuário personalizar notificações, etc. Sobre SPAM, tem sistemas de mensageria para disparar de forma segura sem ser bloqueado. O que usamos aqui é o https://elasticemail.com/

**Comment by carolinesalib** [comment]
@giustin belesma :3 vou criar uma tarefa separada pra isso então, muito thanks

**Comment by anibiamachado** [comment]
@carolinesalib está ok, eu sugiro as seguintes melhorias na tela de notificação:

- ordenar do interesse mais recente para o mais antigo;
- alterar a frase de "Aníbia acabou de registrar interesse..." para "Aníbia registrou interesse...", pois pode ser que o interesse tenha sido registrado a uns 15 dias e a frase não vai combinar :)

**Comment by carolinesalib** [comment]
@anibiamachado faz muito sentido. Ajustado.
