### ISSUE TITLE
Adicionar opção para fechar modal

### ISSUE THREAD

**Issue by carolinesalib** [boacausa/webplatform#117]
Quando aparecer modais no sistema, devemos ter um botão x para ser mais intuitivo para o usuário fecha-lo.

Issue origem: #40

**Comment by anibiamachado** [comment]
@carolinesalib testei com a modal que aparece quando o usuário clica no botão "Adotar" e está ok. Tem mais alguma modal que eu deveria testar?

**Comment by carolinesalib** [comment]
@anibiamachado é só essa modal mesmo
