### ISSUE TITLE
Erro quando exclui pet com interesse em adoção

### ISSUE THREAD

**Issue by carolinesalib** [boacausa/webplatform#131]
**Como reproduzir:**
- Excluir um pet com interesse em adoção
- Ir para a página de interessados em adoção

Erro:
![image](https://user-images.githubusercontent.com/5773360/71416430-98f01780-261d-11ea-971b-bb278a557d1f.png)

**Solução**
- Excluir interesse em adoção e notificação após excluir o pet
- _Ou não excluir o pet, apenas inativar_
  - _Esse gera mais trabalho pois temos que filtrar pets ativos em vários lugares e criar coluna no banco. Pode ser um follow-up_

**Comment by anibiamachado** [comment]
Está ok @carolinesalib. Só me pergunto se, nesse caso, na hora de excluir o pet, não deveria avisar o usuário que tem interesses em adoção e se ele deseja prosseguir com a exclusão mesmo assim. O que acha?

**Comment by carolinesalib** [comment]
@anibiamachado faz sentido. Criei uma issue separada para na segunda milestone implementarmos esta melhoria: https://github.com/boacausa/webplatform/issues/137
