### ISSUE TITLE
Relação entre usuários e ongs

### ISSUE THREAD

**Issue by carolinesalib** [boacausa/webplatform#31]
- [x] Implementar uma relação das ongs e dos usuários que tem acesso a estas;
- [x] Permitir cadastrar usuários para a ong;
  - [x] No cadastro de usuários vai ter checkboxs com as ONGs relacionadas ao usuário permitindo adição/remoção;
  - [x] Usuários admin terão acesso a todas as ONGs; 
- [x] Mostrar somente dados da ong que o usuário tem relação na página administrativa;

**Comment by giustin** [comment]
Oi @carolinesalib !

Testes OK, de acordo com o escopo.
