### ISSUE TITLE
Melhorar CSS da página de ongs

### ISSUE THREAD

**Issue by carolinesalib** [boacausa/webplatform#34]
Adicionar um arquivo CSS exclusivo para essa página e transferir todo o hardcode da view para esse arquivo.

**Comment by nelsonmfinda** [comment]
O projecto boacausa faz parte do [hacktoberfest](https://hacktoberfest.digitalocean.com/)? Estou participando desta iniciativa e gostaria de contribuir.

**Comment by carolinesalib** [comment]
Oi, @nelsonmfinda!

PRs neste projeto contam para o hacktoberfest sim. 👏

**Comment by nelsonmfinda** [comment]
@carolinesalib Ham ok, achei estranho não vi nenhuma label. Poderiam add se possível!

**Comment by carolinesalib** [comment]
@nelsonmfinda que tipo de label? Não entendi.. :( mas de qualquer forma, pelo o que eu li no site do hacktoberfest, qualquer repositório privado conta, então estamos dentro. ;)

**Comment by aoc85** [comment]
@nelsonmfinda está fazendo essa task?

**Comment by nelsonmfinda** [comment]
Sim @aoc85

**Comment by aoc85** [comment]
> Sim @aoc85

@nelsonmfinda , eu mandei um PR com as alterações que tinha feito na página ngos/index.html.erb. Deixei de fora as alterações na ngos/show.html.erb. blz?

**Comment by carolinesalib** [comment]
@nelsonmfinda e @aoc85 adicionei os labels que o github sugeriu para ajudar o pessoal a contribuir, então caso estejam procurando tarefas para começar, podem procurar por issues com as labels "good first issue" e "help wanted".

**Comment by nelsonmfinda** [comment]
@carolinesalib essa _issue_ já foi resolvida pelo @aoc85 certo?

**Comment by carolinesalib** [comment]
Oi, @nelsonmfinda! Já sim, tinha esquecido de fechar. Obrigada :D
