### ISSUE TITLE
Permitir opções de login com Google e Facebook

### ISSUE THREAD

**Issue by carolinesalib** [boacausa/webplatform#36]
- [x] Permitir realizar o login via google
- [x] Permitir realizar o login via facebook
- [x] Verificar problema de domínio no facebook
- [x] Verificar porque o Tiago não consegue fazer login pelo Google

**Comment by carolinesalib** [comment]
@Giustin pode colar um print do problema que ocorre quando tu tenta logar pelo Google? @Anibia-Machado pode testar também?

**Comment by giustin** [comment]
@Caroline-Salib 

![image.png](https://zube.io/files/por-uma-boa-causa/25ad33fdead732482c427fc49b040bde-image.png)

**Comment by giustin** [comment]
@Caroline-Salib 

Google tá indo.. mas depois de logar (que aparentemente não dá erro em tela), não faz login de fato. Nada acontece na verdade, e apenas volta para a home.

**Comment by carolinesalib** [comment]
Oi, @Giustin!

Acredito que agora tanto o login com o facebook quanto com google estão ok.

**Comment by giustin** [comment]
@carolinesalib não estou conseguindo testar isso ainda. Está ocorrendo erro tanto com Facebook quanto Google. Confere as mensagens abaixo:

![image.png](https://zube.io/files/por-uma-boa-causa/08e3bb29f2af15b9bb211d40f08b837e-image.png)
![image.png](https://zube.io/files/por-uma-boa-causa/246f3f41228af5271098c4b7fe047201-image.png)

**Comment by carolinesalib** [comment]
@Giustin parece que o erro acontecia porque você estava usando http ao invés de https, mas usei uma mágica do rails pra forçar https sempre, pode verificar novamente?

Thanks @tiagocamargo pelo help! ❤️
