### ISSUE TITLE
Bug ao usar a opção Logout na área administrativa das ONGs

### ISSUE THREAD

**Issue by carolinesalib** [boacausa/webplatform#37]
Para simular, fazer login e depois clicar na opção Logout, no canto direito superior.

O sistema é redirecionado para este endereço e causa o erro abaixo:
https://porumaboacausa.herokuapp.com/ngo_area/login.html

![erro.png](https://zube.io/files/por-uma-boa-causa/5c6c3156dde5d51fc6a1e5b9f6c7891a-erro.png)

**Comment by nelsonmfinda** [comment]
@carolinesalib Não vejo o link para cadastro. E outro problema é:
Ao fazer login com dados inválidos ou via OAuth(Facebook ou Google) o OAuth retorna o erro 400.
![Imagem com o erro](https://user-images.githubusercontent.com/31723750/46385144-7aa0a380-c688-11e8-8493-98a05b538d4c.png)

**Comment by carolinesalib** [comment]
Outra forma de fazer login:
https://porumaboacausa.herokuapp.com/users/sign_up

Vou criar um card para deixar essa url disponível na tela de login.
