### ISSUE TITLE
Processo de registro de adoção por um usuário logado e notificações

### ISSUE THREAD

**Issue by giustin** [boacausa/webplatform#40]
**Objetivo**

Quando um usuário logado registrar o interesse em um pet, o processo deve funcionar da seguinte maneira:

- [x] Quando o usuário clicar no botão, devemos emitir a mensagem de sucesso para ele informando o seguinte: "Que legal! Você é mais um terráqueo agindo por uma boa causa! Em breve os responsáveis do seu futuro amiguinho entrarão em contato.
- [ ] Quando a pessoa confirmar que tem interesse, precisamos que ela auto declare que tem algumas condições mínimas para ter um animal: Será um "Aceito os termos" com alguns tópicos que a ONG piloto ficou de nos enviar para colocarmos no processo.
  - Criado issue separada para isso: https://github.com/boacausa/webplatform/issues/112
- [x] Na área de administração da ONG, criar uma seção onde seja possível consultar os pedidos de adoção, constando Nome do interessado, Telefone, E-mail, Pet escolhido e Data da solicitação.
- [ ] Na área de administração, exibir uma notificação sempre que alguém fazer um pedido de adoção pela página. Sugestão "O usuário Tiago Giusti acabou de registrar interesse em um pet da sua ONG". Ou, se quiser e não for complexo, já colocar o nome do pet na mensagem. Ao clicar na mensagem, levar para a página que lista os pedidos de adoção efetuado.
  - Criado issue separada para isso: https://github.com/boacausa/webplatform/issues/113

**Resultado**
Screenshot dos cards de adoção
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/5773360/69435837-8a9c9c00-0cfd-11ea-9586-09eb3cbe0054.png">

Screenshot da página de interessados em adoção
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/5773360/69354727-d2f48500-0c3d-11ea-91e3-89c4397fb063.png">

**Comment by giustin** [comment]
@Caroline-Salib adicionei o segundo item aqui, que foi decorrente da reunião com a ONG. O documento modelo eu separei em outra task para solicitarmos para a ONG nos enviar.

**Comment by carolinesalib** [comment]
@Giustin @Tamara-Selau será que os termos e condições para adoção pode ser um campo texto no cadastro da ONG?

Quem sabe assim pra começar e no futuro pensamos numa forma mais "burocrática" pro usuário aceitar adotar, tipo assinatura eletrônica e versionamento dos termos, não sei..

**Comment by giustin** [comment]
De acordo @carolinesalib, vamos seguir simples pra poder gerar aprendizado operando.

O que ficar fora do escopo, por favor, registra nas nossas tasks de ideias para o futuro.

**Comment by carolinesalib** [comment]
WIP DEV TODO list:

- [x] Add ONG details
- [x] Link ONG to ONG's page
- [x] Add pet photo
- [ ] Adjust pet photo size
- [x] Add bigger description on seed
- [x] Why seed only creates "femeas"
- [x] City details (use ONG address)
- [x] Labels information
- [ ] What is the order we should use for listing pets?
- [ ] Filter for City
- [ ] Filter for NGO
- [ ] Filter for words (change to order?)
- [ ] Responsive layout
- [ ] Modal for adoption
  - [ ] User control (only enable if you're logged in)
  - [ ] Option to register interest
- [ ] Register interest button
  - [ ] Notification of interest to NGO (daily email with new interested people?)
  - [ ] List of interested people
  - [ ] E-mail to notify new interest with link to interest page
- [ ] Show error message if something went wrong when click in adopt
- [ ] Disable adoption button when user already selected the pet for adoption
- [ ] Update adoption message


**Quality**

- [ ] Search for TODOs 
- [ ] Not cause problems on codeclimate
- [ ] Test react components

**Comment by carolinesalib** [comment]
Screenshot da lista de interesse em adoção.
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/5773360/69354641-accee500-0c3d-11ea-9c44-77ece6bfeaed.png">

**Comment by anibiamachado** [comment]
@carolinesalib, segue resultado dos testes dos itens 1 e 3 da issue (alguns são melhorias):

- Mudar o nome do botão "adote" para "adotar", pois um verbo inspira ação, que é o caso;
- Ao clicar em "adote", antes de emitir a mensagem final, pedir uma confirmação se o usuário deseja prosseguir (sim/não), para só depois mostrar a mensagem de que a ONG acabou de saber de seu interesse;
- Na caixa da mensagem final (que mostra que a ONG acabou de saber de seu interesse), ter um botão fechar;
- Mudar o nome do menu "Interesse em adoção" para "Interessados em adoção". Com isso poderia ser tirado o label "Lista de usuários e pets";
- Na área da ONG, campo "Dat"a mostrou essa informação "qui, 21 de novembro de 2019, 18:55:11 +0000", retirar a informação ":11 +0000", pois não agrega e pode gerar confusão;
- No mesmo campo da data de interesse de adoção, o horário que aparece está estranho, com umas 2 horas a mais do meu notebook;
- Na área da ONG, o telefone que apareceu relacionado ao meu usuário é um que desconheço ((48) 89888-9898), de onde essa informação é pega?

**Comment by carolinesalib** [comment]
Criado issue para todas as coisas que faltam ser feitas nessa issue.
