### ISSUE TITLE
Adicionar imagem default para quando a imagem não puder ser carregada

### ISSUE THREAD

**Issue by carolinesalib** [boacausa/webplatform#43]
Hoje quando a imagem do pet para adoção não pode ser carregada, o card fica feio. Devemos ter uma imagem de fallback.

![image.png](https://zube.io/files/por-uma-boa-causa/c87ea1e61d6e8ceab2b05f3e3eebc757-image.png)

Observação: por enquanto pode ser uma imagem qualquer da internet até que a UILab disponibilize isto pra gente.

**Comment by carolinesalib** [comment]
https://github.com/boacausa/webplatform/pull/75

**Comment by carolinesalib** [comment]
Estou usando a imagem abaixo temporariamente como "imagem não encontrada". 

![image.png](https://zube.io/files/por-uma-boa-causa/366dadb1da202538ae13329ba34d9006-image.png)

**Comment by anibiamachado** [comment]
@carolinesalib testes ok.
