### ISSUE TITLE
Cadastro de usuários comuns e grupo de permissão

### ISSUE THREAD

**Issue by giustin** [boacausa/webplatform#46]
- [x] Ter grupo de permissões admin, ong, usuários normais;
- [x] Permitir realizar cadastro apenas de usuários normais pelo site;
- [x] O cadastro de usuários poderá ser via google, facebook ou cadastro;
- [x] Pessoas com permissão de usuário não terão acesso a página administrativa;

*Registrar as pessoas físicas e jurídicas que fizeram algum tipo de doação: financeira, ração, medicamentos, etc. Para pessoas físicas, podemos ver uma forma de marcar ela como doadora, que pode ser o Administrador da ONG ou a própria pessoa indicar que é doadora. No caso de empresas, permitir que o admin cadastre empresas que doam com a logo, nome e cidade.*

*As pessoas podem autorizar serem exibidas junto a ONG, para serem conhecidas. As empresas, também dar um destaque especial, impulsionando mais doações;*

Após a realização deste card, será possível seguir com as melhorias na página de adoção, permitindo usuários aplicarem para adotar animais, etc..

**Comment by carolinesalib** [comment]
Oi, @Giustin!

Tudo bem, assim que eu descobrir o problema do login com o google você pode continuar com esta task.

**Comment by giustin** [comment]
@carolinesalib Testes OK. 

O que teremos que ajustar são as traduções do login com oAuth, mas podemos tratar em outra task.
