### ISSUE TITLE
Relacionar opções de adoção com ongs

### ISSUE THREAD

**Issue by carolinesalib** [boacausa/webplatform#59]
Do jeito que está hoje, os pets cadastrados não estão relacionados com nenhuma ONG.

- [x] Adicionar relação entre pets e ONGs;
- [x] Só mostrar Pets da mesma ONG que o usuário na listagem de pets da página administrativa;
  - [x] Usuários admin podem ver todos os pets;
- [x] Adicionar campo obrigatório de de ONG ao registrar um Pet;
- [x] Após adicionar em produção, migrar os pets cadastrados sem ong para uma ong aleatória;

**Comment by carolinesalib** [comment]
https://github.com/boacausa/webplatform/pull/60

**Comment by anibiamachado** [comment]
@carolinesalib:

- Na aba "Pets", mudar o nome dos campos "#" e "Name" para "Código" e "Nome";
- Sobre esse item da issue: "Após adicionar em produção, migrar os pets cadastrados sem ong para uma ong aleatória", não seria arriscado fazer isso, considerando que a informação pode ficar errada na base?

**Comment by carolinesalib** [comment]
@anibiamachado 

* Ajustado nome dos campos
* Sobre migrar os pets para ongs aleatórias, não temos dados ainda em produção então não é um problema. E não é mais possível cadastrar pet sem ONG, então não precisamos rodar esse script novamente

**Comment by anibiamachado** [comment]
@carolinesalib o campo "Name" não foi alterado.
