### ISSUE TITLE
Opção Forgot your password não está funcionando

### ISSUE THREAD

**Issue by giustin** [boacausa/webplatform#61]
Tentei usar a opção Esqueceu sua senha e obtive uma tela de erro.

Passos para simular:
1. Acesse a página Forgot your password: http://porumaboacausa.herokuapp.com/users/password/new
2. Informe um email existente na base;
3. Clique em Send me...
4. Note a página de erro, conforme a imagem abaixo:

![image.png](https://zube.io/files/por-uma-boa-causa/33bca9adf4c4356329813282803348f8-image.png)

**Comment by giustin** [comment]
@carolinesalib vou deixar esta no backlog porque é essencial para o MVP. Talvez precisemos nos reunir e montar uma próxima sprint né? Não sei se estas questões tem relação ou podem mudar, quando fizermos o deploy em produção oficial.

**Comment by carolinesalib** [comment]
Corrigido nos pull-requests:
https://github.com/boacausa/webplatform/pull/70
https://github.com/boacausa/webplatform/pull/71
