### ISSUE TITLE
Erro ao criar a base de dados

### ISSUE THREAD

**Issue by nelsonmfinda** [boacausa/webplatform#78]
![image](https://user-images.githubusercontent.com/31723750/56402879-12499600-6257-11e9-92fc-b9b8db3ca887.png)
@carolinesalib  não seria melhor usar a configuração padrão do _Rails 5.2_ para o arquivo `boacausa-webapp/config/database.yml`?
Já tenho um usuário na minha máquina, e a senha sugerida não atende os requisitos da minha configuração local.

**Comment by carolinesalib** [comment]
Oi, @nelsonmfinda!

Acredito que na configuração padrão do Rails 5.2 seja utilizado o sqlite como base de dados. Como a gente já tem o projeto no ar na heroku (que não aceita sqlite) e por n outros motivos é preferível usar o postgresql. Pra facilitar eu criei um arquivo docker-compose.yml que já contem um container com um banco de dados postgresql para ser usado. Como você fez para instalar o seu banco de dados postgres? Lembra se criou algum usuário e senha? 

Caso queira trocar a senha da configuração [1], você pode criar uma nova ENV e para isto e comitar/

[1] https://github.com/boacausa/webplatform/blob/master/config/database.yml

**Comment by nelsonmfinda** [comment]
@carolinesalib esse não é o problema, em `development` não precisava colocar um usuário e senha(Minha senha e usuário para o *PostgreSQL* são diferentes) e por outra, para que funcione eu tinha que passar meu _usuário_ e _senha_, e ficaria exposto pra qual quer um... Em `production` por exemplo, pode usar variáveis de ambiente.

**Comment by carolinesalib** [comment]
@nelsonmfinda mas neste caso como você informa ao postgresql o usuário e senha para acesso a base de dados local?

**Comment by nelsonmfinda** [comment]
Não.

**Comment by carolinesalib** [comment]
@nelsonmfinda entendi sua sugestão agora! Pode enviar um PR alterando o arquivo? Já fica como primeira contribuição ao projeto. ☺️

**Comment by nelsonmfinda** [comment]
Sim @carolinesalib obrigado!
