### ISSUE TITLE
Fix login when using boacausa.org

### ISSUE THREAD

**Issue by carolinesalib** [boacausa/webplatform#88]
The login with facebook and google might be broken when using http://www.boacausa.org because of the new URL.

**Comment by carolinesalib** [comment]
Acho que eu corrigi isso em algum momento e nem lembro mais. Parece estar funcionando.

**Comment by anibiamachado** [comment]
@carolinesalib quando faço o login com o Face, a URL apresenta caracteres especiais, veja:

https://www.boacausa.org/#_=_

Com o gmail a URL ficou assim:

https://www.boacausa.org/#

Aproveitando:

- Na tela de login, a opção de entrar com o Google está com um nome distorcido: "Sign in with GoogleOauth2".

**Comment by carolinesalib** [comment]
@anibiamachado ajustado url. A parte de "Sign in with GoogleOauth2" vou ajuster quando a gente redesenhar a UI porque vamos utilizar novos botões.

**Comment by anibiamachado** [comment]
Está ok.
